### ISSUE TITLE
should I do recoded?

### ISSUE THREAD

**Issue by wocao1111** [ApourtArtt/NtHkBypass#1]
still not work for heartbeat function to bypass anti cheat

**Comment by ApourtArtt** [comment]
Hello, sorry seems like I missed your issue.

The goal of this repository is not to replace the behaviour of their anticheat - but to allow me to inject any DLL for further research.
This repository only disable the DLL (so the heartbeat is not sent anymore, as you noticed)

If your goal is not to do researchs but to cheat, I invite you to replace NOT the anticheat but EWSF.EWS.
Your EWSF.EWS would need to define two functions: ShowNostaleSplash and FreeNostaleSplash.
EWSF.EWS is injected before the anticheat runs, so you can basically do whatever you want in this EWSF.EWS
